"""Add campo senha na tabela de Aluno

Revision ID: 75c4ee1711c2
Revises: 76f45c344873
Create Date: 2023-10-23 16:37:11.277121

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '75c4ee1711c2'
down_revision = '76f45c344873'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('aluno', schema=None) as batch_op:
        batch_op.add_column(sa.Column('senha', sa.String(length=100), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('aluno', schema=None) as batch_op:
        batch_op.drop_column('senha')

    # ### end Alembic commands ###
